toolbox:
  hosts:
    toolbox:
      ansible_host: localhost
      ansible_connection: ansible.builtin.local

hypervisor:
  hosts:
    proxmox:
      ansible_host: 192.168.16.2
      ansible_user: root

almalinux:
  hosts:
    almalinux_infra:
      ansible_host: 192.168.16.101
      ansible_user: almalinux
    almalinux_main:
      ansible_host: 192.168.16.102
      ansible_user: almalinux
    almalinux_media:
      ansible_host: 192.168.16.103
      ansible_user: almalinux
