# IMPORTANT: some containers will fail if you don't set a valid timezone
# Region/City - https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Amsterdam

# Containers to install
containers:
  - technitium_dns
  - portainer
  - pterodactyl

# Usually user=group and uid=gid. A user always needs the same uid
# Multiple apps with the same user/uid configuration are allowed
users:
  podman: &podman
    name: podman
    group: podman
    uid: 2000
    gid: 2000
    home: /home/podman

  technitium_dns:
    <<: *podman

  portainer:
    <<: *podman

  pterodactyl:
    name: pterodactyl
    group: pterodactyl
    uid: 2003
    gid: 2003
    home: /home/pterodactyl
