# Containers to install
containers:
  - technitium_dns
  - nginx_proxy_manager

# Usually user=group and uid=gid. A user always needs the same uid
# Multiple apps with the same user/uid configuration are allowed
users:
  podman: &podman
    name: podman
    group: podman
    uid: 2000
    gid: 2000
    home: /home/podman

  technitium_dns:
    <<: *podman

  nginx_proxy_manager:
    name: root
    group: root
    uid: 0
    gid: 0
    home: /root/
