- name: Install podman with containers
  become: true
  block:
    - name: Install podman
      ansible.builtin.dnf:
        name: podman
        state: present

    - name: Create subuid entry for containers user
      ansible.builtin.lineinfile:
        path: /etc/subuid
        regexp: "^containers:.*$"
        line: "containers:2147483647:2147483648"

    - name: Create subgid entry for containers user
      ansible.builtin.lineinfile:
        path: /etc/subgid
        regexp: "^containers:.*$"
        line: "containers:2147483647:2147483648"

    - name: Install all containers
      ansible.builtin.include_tasks: "setup.yml"
      vars:
        user: "{{ users[container_name] }}"
      loop: "{{ containers }}"
      loop_control:
        loop_var: container_name
