- name: Install podman with containers
  become: true
  block:
    - name: Install podman
      ansible.builtin.dnf:
        name: podman
        state: present

    - name: Install all containers
      ansible.builtin.include_tasks: "setup.yml"
      vars:
        user: "{{ users[container_name] }}"
      loop: "{{ containers }}"
      loop_control:
        loop_var: container_name
