- name: Log in as the nginx_proxy_manager user
  become: true
  become_user: "{{ user.name }}"
  vars:
    container:
      name: nginx-proxy-manager
      folder: nginx-proxy-manager
      files:
        - nginx-proxy-manager.container
      envfiles:
        - nginx-proxy-manager.env
      service: nginx-proxy-manager
  block:
    - name: "Copy {{ container.name }} container files"
      ansible.builtin.import_tasks: meta/copy-files.yml

    - name: "Start {{ container.name }} container"
      ansible.builtin.import_tasks: meta/start-container.yml
