- name: Log in as the nginx_proxy_manager user
  become: true
  become_user: "{{ user.name }}"
  vars:
    container:
      name: nginx_proxy_manager
      file: nginx-proxy-manager/nginx-proxy-manager
      envfile: true
  block:
    - name: "Copy {{ container.name }} container files"
      ansible.builtin.import_tasks: meta/copy-files.yml

    - name: "Start {{ container.name }} container"
      ansible.builtin.import_tasks: meta/start-container.yml
