- name: "Log in as the technitium_dns user"
  become: true
  become_user: "{{ user.name }}"
  vars:
    container:
      name: dns-server
      folder: technitium-dns
      files:
        - dns-server.container
      envfiles:
        - dns-server.env
      service: dns-server
  block:
    - name: "Copy {{ container.name }} container files"
      ansible.builtin.import_tasks: meta/copy-files.yml

    - name: "Start {{ container.name }} container"
      ansible.builtin.import_tasks: meta/start-container.yml
