- name: "Copy {{ container.name }} container files"
  become: true
  become_user: "{{ user.name }}"
  block:
    - name: "Copy templated {{ container.name }} container files"
      ansible.builtin.template:
        src: "quadlets/{{ container.folder }}/{{ item }}"
        dest: "{{ '/etc/containers/systemd/' if user.uid == 0 else user.home + '/.config/containers/systemd/' }}"
        mode: "644"
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
      loop: "{{ container.files }}"

    - name: "Copy templated {{ container.name }} environment files"
      ansible.builtin.template:
        src: "quadlets/{{ container.folder }}/{{ item }}"
        dest: "{{ '/etc/containers/environment/' if user.uid == 0 else user.home + '/.config/containers/environment/' }}"
        mode: "644"
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
      loop: "{{ container.envfiles }}"
