[[registry]]
location = "docker.io"

[[registry.mirror]]
location = "{{ harbor.hostname }}/docker-hub"
pull-from-mirror = "all"

[[registry]]
location = "ghcr.io"

[[registry.mirror]]
location = "{{ harbor.hostname }}/ghcr"
pull-from-mirror = "all"
